[Constructor(double x, double y)]
interface Vector2d {
    attribute double x;
    attribute double y;
    readonly attribute double angle;
    Vector2d add(Vector2d vector);
    double dotProduct(Vector2d vector);
};
